{% set name = "diffstar" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffstar/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 1ec939cf10fbf68a14cea0d7d9014852d09089afb0a7d4d388e43f4bc514c4a0

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
    - setuptools_scm
  run:
    - python >={{ python_min }}
    - numpy
    - jax
    - diffmah >=0.5.0
    - h5py

test:
  requires:
    - python {{ python_min }}
  imports:
    - diffstar

about:
  home: https://github.com/ArgonneCPAC/diffstar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable star formation histories

extra:
  recipe-maintainers:
    - beckermr
