{% set name = "diffstar" %}
{% set version = "0.1.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffstar/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b1572b86e6d60261b60657e0657be63712f3971cfdfe3933f83cfdc045ab9f83

build:
  number: 1
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - jax
    - diffmah >=0.3.0

test:
  imports:
    - diffstar

about:
  home: https://github.com/ArgonneCPAC/diffstar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Differentiable star formation histories

extra:
  recipe-maintainers:
    - beckermr
