{% set name = "diffstar" %}
{% set version = "0.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffstar/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 5cad885fb79f3c856e6d1d943b1af35d4b8026dd26f3efbbaab132c45c825b06

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools_scm
  run:
    - python >=3.6
    - numpy
    - jax
    - diffmah >=0.3.0
    - h5py

test:
  imports:
    - diffstar

about:
  home: https://github.com/ArgonneCPAC/diffstar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE.rst
  summary: Differentiable star formation histories

extra:
  recipe-maintainers:
    - beckermr
