{% set name = "diffstar" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ArgonneCPAC/diffstar/archive/refs/tags/v{{ version }}.tar.gz
  sha256: 6e98cdf088aff2a2bd2b4cedd54a0822459b42e4a151164026df22062c0f8098

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - numpy
    - jax
    - diffmah >=0.3.0

test:
  imports:
    - diffstar

about:
  home: https://github.com/ArgonneCPAC/diffstar
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: Differentiable star formation histories

extra:
  recipe-maintainers:
    - beckermr
